all:
  children:
    nodes:
      hosts:
        node1-boa1:
          ansible_host: 10.1.240.8
          bmc_ip: 10.1.240.9
    boa1:
      hosts:
        node1-boa1:
    metal:
      hosts:
        node1-boa1: